### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by blitzgneisserin**

### CODE REVIEW

**Comment by hanatos** [comment]
great! thanks for sharing. could you post at least one of the generated jpg files that shows the fit so we can double check whether it actually worked well?

**Comment by blitzgneisserin** [comment]
Olympus-E-M5 Mark III-800 nprof
Olympus-E-M5 Mark III-400 nprof
Olympus-E-M5 Mark III-200 nprof
Olympus-E-M5 Mark III-1600 nprof
Olympus-E-M5 Mark III-3200 nprof
Olympus-E-M5 Mark III-6400 nprof
Olympus-E-M5 Mark III-12800 nprof
Olympus-E-M5 Mark III-25600 nprof

**Comment by blitzgneisserin** [comment]
I got this output during the execution of noise-profile.sh:

`[nprof] WARN: reducing expectations 1x because we collected very few valid samples!`

**Comment by hanatos** [comment]
looking good. the output is pretty arbitrary, only reducing too many times is really worrying.

**Pull request merged**
